name: Node.js CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        # This will now find package-lock.json in the root directory

    - name: Install dependencies
      run: npm ci

    - name: Build all projects
      run: npm run build --if-present

    - name: Run lints
      run: npm run lint --if-present
      continue-on-error: true

  build-omni-core:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Omni Core
      run: npm run build:omni

  build-firebase-functions:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'  # Firebase Functions requires Node 18
        cache: 'npm'
        
    - name: Install dependencies  
      run: npm ci
      
    - name: Build Firebase Functions
      run: npm run build:functions
      continue-on-error: true  # Allow TypeScript errors for now